<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use OnfonDeveloperV1Lib\Controllers\AuthenticationController;
use OnfonDeveloperV1Lib\Controllers\BalanceSendSMSController;
use OnfonDeveloperV1Lib\Controllers\ComposeSMSController;
use OnfonDeveloperV1Lib\Controllers\ContactsController;
use OnfonDeveloperV1Lib\Controllers\GroupController;
use OnfonDeveloperV1Lib\Controllers\PurchaseController;
use OnfonDeveloperV1Lib\Controllers\SenderidController;
use OnfonDeveloperV1Lib\Controllers\SMSCampaignsController;
use OnfonDeveloperV1Lib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class OnfonDeveloperV1Client implements ConfigurationInterface
{
    private $authentication;

    private $balanceSendSMS;

    private $group;

    private $contacts;

    private $senderid;

    private $sMSCampaigns;

    private $composeSMS;

    private $purchase;

    private $bearerAuthManager;

    private $config;

    private $client;

    /**
     * @see OnfonDeveloperV1ClientBuilder::init()
     * @see OnfonDeveloperV1ClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->bearerAuthManager = new BearerAuthManager(
            $this->config['accessToken'] ?? ConfigurationDefaults::ACCESS_TOKEN
        );
        $this->client = ClientBuilder::init(new HttpClient(Configuration::init($this)))
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('APIMATIC 3.0')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::SERVER_1)
            ->authManagers(['global' => $this->bearerAuthManager])
            ->build();
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return OnfonDeveloperV1ClientBuilder OnfonDeveloperV1ClientBuilder instance
     */
    public function toBuilder(): OnfonDeveloperV1ClientBuilder
    {
        return OnfonDeveloperV1ClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->accessToken($this->bearerAuthManager->getAccessToken())
            ->httpCallback($this->config['httpCallback'] ?? null);
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getBearerAuthCredentials(): ?BearerAuthCredentials
    {
        return $this->bearerAuthManager;
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see OnfonDeveloperV1ClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see OnfonDeveloperV1ClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::SERVER_1): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Authentication Controller
     */
    public function getAuthenticationController(): AuthenticationController
    {
        if ($this->authentication == null) {
            $this->authentication = new AuthenticationController($this->client);
        }
        return $this->authentication;
    }

    /**
     * Returns Balance Send SMS Controller
     */
    public function getBalanceSendSMSController(): BalanceSendSMSController
    {
        if ($this->balanceSendSMS == null) {
            $this->balanceSendSMS = new BalanceSendSMSController($this->client);
        }
        return $this->balanceSendSMS;
    }

    /**
     * Returns Group Controller
     */
    public function getGroupController(): GroupController
    {
        if ($this->group == null) {
            $this->group = new GroupController($this->client);
        }
        return $this->group;
    }

    /**
     * Returns Contacts Controller
     */
    public function getContactsController(): ContactsController
    {
        if ($this->contacts == null) {
            $this->contacts = new ContactsController($this->client);
        }
        return $this->contacts;
    }

    /**
     * Returns Senderid Controller
     */
    public function getSenderidController(): SenderidController
    {
        if ($this->senderid == null) {
            $this->senderid = new SenderidController($this->client);
        }
        return $this->senderid;
    }

    /**
     * Returns SMS Campaigns Controller
     */
    public function getSMSCampaignsController(): SMSCampaignsController
    {
        if ($this->sMSCampaigns == null) {
            $this->sMSCampaigns = new SMSCampaignsController($this->client);
        }
        return $this->sMSCampaigns;
    }

    /**
     * Returns Compose SMS Controller
     */
    public function getComposeSMSController(): ComposeSMSController
    {
        if ($this->composeSMS == null) {
            $this->composeSMS = new ComposeSMSController($this->client);
        }
        return $this->composeSMS;
    }

    /**
     * Returns Purchase Controller
     */
    public function getPurchaseController(): PurchaseController
    {
        if ($this->purchase == null) {
            $this->purchase = new PurchaseController($this->client);
        }
        return $this->purchase;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [Environment::PRODUCTION => [Server::SERVER_1 => 'https://apis.onfonmedia.co.ke']];
}
