<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Tests\Controllers;

use Core\TestCase\TestParam;
use OnfonDeveloperV1Lib\Controllers\AuthenticationController;
use OnfonDeveloperV1Lib\Exceptions;
use OnfonDeveloperV1Lib\Models;

class AuthenticationControllerTest extends BaseTestController
{
    /**
     * @var AuthenticationController AuthenticationController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getAuthenticationController();
    }

    public function testAuthorization()
    {
        // Parameters for the API call
        $body = TestParam::object(
            "{\r\n  \"apiUsername\": \"username\",\r\n  \"apiPassword\": \"apiPass\"\r\n}",
            Models\AuthorizationRequest::class
        );

        // Perform API call
        try {
            self::$controller->authorization($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
