<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Tests\Controllers;

use OnfonDeveloperV1Lib\Controllers\PurchaseController;
use OnfonDeveloperV1Lib\Exceptions;

class PurchaseControllerTest extends BaseTestController
{
    /**
     * @var PurchaseController PurchaseController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getPurchaseController();
    }

    public function testListPurchases()
    {
        // Perform API call
        try {
            self::$controller->listPurchases();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
