<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class AuthorizationRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $apiUsername;

    /**
     * @var string
     */
    private $apiPassword;

    /**
     * @param string $apiUsername
     * @param string $apiPassword
     */
    public function __construct(string $apiUsername, string $apiPassword)
    {
        $this->apiUsername = $apiUsername;
        $this->apiPassword = $apiPassword;
    }

    /**
     * Returns Api Username.
     */
    public function getApiUsername(): string
    {
        return $this->apiUsername;
    }

    /**
     * Sets Api Username.
     *
     * @required
     * @maps apiUsername
     */
    public function setApiUsername(string $apiUsername): void
    {
        $this->apiUsername = $apiUsername;
    }

    /**
     * Returns Api Password.
     */
    public function getApiPassword(): string
    {
        return $this->apiPassword;
    }

    /**
     * Sets Api Password.
     *
     * @required
     * @maps apiPassword
     */
    public function setApiPassword(string $apiPassword): void
    {
        $this->apiPassword = $apiPassword;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['apiUsername'] = $this->apiUsername;
        $json['apiPassword'] = $this->apiPassword;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
