<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class Client implements \JsonSerializable
{
    /**
     * @var string
     */
    private $clientId;

    /**
     * @var string
     */
    private $clientNames;

    /**
     * @var string
     */
    private $clientStatus;

    /**
     * @param string $clientId
     * @param string $clientNames
     * @param string $clientStatus
     */
    public function __construct(string $clientId, string $clientNames, string $clientStatus)
    {
        $this->clientId = $clientId;
        $this->clientNames = $clientNames;
        $this->clientStatus = $clientStatus;
    }

    /**
     * Returns Client Id.
     */
    public function getClientId(): string
    {
        return $this->clientId;
    }

    /**
     * Sets Client Id.
     *
     * @required
     * @maps clientId
     */
    public function setClientId(string $clientId): void
    {
        $this->clientId = $clientId;
    }

    /**
     * Returns Client Names.
     */
    public function getClientNames(): string
    {
        return $this->clientNames;
    }

    /**
     * Sets Client Names.
     *
     * @required
     * @maps clientNames
     */
    public function setClientNames(string $clientNames): void
    {
        $this->clientNames = $clientNames;
    }

    /**
     * Returns Client Status.
     */
    public function getClientStatus(): string
    {
        return $this->clientStatus;
    }

    /**
     * Sets Client Status.
     *
     * @required
     * @maps clientStatus
     */
    public function setClientStatus(string $clientStatus): void
    {
        $this->clientStatus = $clientStatus;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['clientId']     = $this->clientId;
        $json['clientNames']  = $this->clientNames;
        $json['clientStatus'] = $this->clientStatus;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
