<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class Contact2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $names;

    /**
     * @param string $names
     */
    public function __construct(string $names)
    {
        $this->names = $names;
    }

    /**
     * Returns Names.
     */
    public function getNames(): string
    {
        return $this->names;
    }

    /**
     * Sets Names.
     *
     * @required
     * @maps names
     */
    public function setNames(string $names): void
    {
        $this->names = $names;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['names'] = $this->names;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
