<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class Contact implements \JsonSerializable
{
    /**
     * @var string
     */
    private $phone;

    /**
     * @var string
     */
    private $groupId;

    /**
     * @param string $phone
     * @param string $groupId
     */
    public function __construct(string $phone, string $groupId)
    {
        $this->phone = $phone;
        $this->groupId = $groupId;
    }

    /**
     * Returns Phone.
     */
    public function getPhone(): string
    {
        return $this->phone;
    }

    /**
     * Sets Phone.
     *
     * @required
     * @maps phone
     */
    public function setPhone(string $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * Returns Group Id.
     */
    public function getGroupId(): string
    {
        return $this->groupId;
    }

    /**
     * Sets Group Id.
     *
     * @required
     * @maps groupId
     */
    public function setGroupId(string $groupId): void
    {
        $this->groupId = $groupId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['phone']   = $this->phone;
        $json['groupId'] = $this->groupId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
