<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class Group2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $groupId;

    /**
     * @var string
     */
    private $groupName;

    /**
     * @param string $groupId
     * @param string $groupName
     */
    public function __construct(string $groupId, string $groupName)
    {
        $this->groupId = $groupId;
        $this->groupName = $groupName;
    }

    /**
     * Returns Group Id.
     */
    public function getGroupId(): string
    {
        return $this->groupId;
    }

    /**
     * Sets Group Id.
     *
     * @required
     * @maps groupId
     */
    public function setGroupId(string $groupId): void
    {
        $this->groupId = $groupId;
    }

    /**
     * Returns Group Name.
     */
    public function getGroupName(): string
    {
        return $this->groupName;
    }

    /**
     * Sets Group Name.
     *
     * @required
     * @maps groupName
     */
    public function setGroupName(string $groupName): void
    {
        $this->groupName = $groupName;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['groupId']   = $this->groupId;
        $json['groupName'] = $this->groupName;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
