<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class SendSMSRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $to;

    /**
     * @var string
     */
    private $from;

    /**
     * @var string
     */
    private $content;

    /**
     * @var string
     */
    private $dlr;

    /**
     * @var string
     */
    private $dlrUrl;

    /**
     * @var int
     */
    private $dlrLevel;

    /**
     * @param string $to
     * @param string $from
     * @param string $content
     * @param string $dlr
     * @param string $dlrUrl
     * @param int $dlrLevel
     */
    public function __construct(string $to, string $from, string $content, string $dlr, string $dlrUrl, int $dlrLevel)
    {
        $this->to = $to;
        $this->from = $from;
        $this->content = $content;
        $this->dlr = $dlr;
        $this->dlrUrl = $dlrUrl;
        $this->dlrLevel = $dlrLevel;
    }

    /**
     * Returns To.
     */
    public function getTo(): string
    {
        return $this->to;
    }

    /**
     * Sets To.
     *
     * @required
     * @maps to
     */
    public function setTo(string $to): void
    {
        $this->to = $to;
    }

    /**
     * Returns From.
     */
    public function getFrom(): string
    {
        return $this->from;
    }

    /**
     * Sets From.
     *
     * @required
     * @maps from
     */
    public function setFrom(string $from): void
    {
        $this->from = $from;
    }

    /**
     * Returns Content.
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * Sets Content.
     *
     * @required
     * @maps content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * Returns Dlr.
     */
    public function getDlr(): string
    {
        return $this->dlr;
    }

    /**
     * Sets Dlr.
     *
     * @required
     * @maps dlr
     */
    public function setDlr(string $dlr): void
    {
        $this->dlr = $dlr;
    }

    /**
     * Returns Dlr Url.
     */
    public function getDlrUrl(): string
    {
        return $this->dlrUrl;
    }

    /**
     * Sets Dlr Url.
     *
     * @required
     * @maps dlr-url
     */
    public function setDlrUrl(string $dlrUrl): void
    {
        $this->dlrUrl = $dlrUrl;
    }

    /**
     * Returns Dlr Level.
     */
    public function getDlrLevel(): int
    {
        return $this->dlrLevel;
    }

    /**
     * Sets Dlr Level.
     *
     * @required
     * @maps dlr-level
     */
    public function setDlrLevel(int $dlrLevel): void
    {
        $this->dlrLevel = $dlrLevel;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['to']        = $this->to;
        $json['from']      = $this->from;
        $json['content']   = $this->content;
        $json['dlr']       = $this->dlr;
        $json['dlr-url']   = $this->dlrUrl;
        $json['dlr-level'] = $this->dlrLevel;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
