<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class SuccessfulResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $messageId;

    /**
     * @param string $messageId
     */
    public function __construct(string $messageId)
    {
        $this->messageId = $messageId;
    }

    /**
     * Returns Message Id.
     */
    public function getMessageId(): string
    {
        return $this->messageId;
    }

    /**
     * Sets Message Id.
     *
     * @required
     * @maps message_id
     */
    public function setMessageId(string $messageId): void
    {
        $this->messageId = $messageId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['message_id'] = $this->messageId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
