<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Controllers;

use Core\Request\Parameters\BodyParam;
use CoreInterfaces\Core\Request\RequestMethod;
use OnfonDeveloperV1Lib\Exceptions\ApiException;
use OnfonDeveloperV1Lib\Models\AuthorizationRequest;

class AuthenticationController extends BaseController
{
    /**
     * @param AuthorizationRequest $body
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function authorization(AuthorizationRequest $body): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v1/authorization')
            ->auth('global')
            ->parameters(BodyParam::init($body));

        $this->execute($_reqBuilder);
    }
}
