<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Tests;

use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): \OnfonDeveloperV1Lib\OnfonDeveloperV1Client
    {
        $clientBuilder = \OnfonDeveloperV1Lib\OnfonDeveloperV1ClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        \OnfonDeveloperV1Lib\OnfonDeveloperV1ClientBuilder $builder
    ): \OnfonDeveloperV1Lib\OnfonDeveloperV1ClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        \OnfonDeveloperV1Lib\OnfonDeveloperV1ClientBuilder $builder
    ): \OnfonDeveloperV1Lib\OnfonDeveloperV1ClientBuilder {
        $timeout = getenv('ONFON_DEVELOPER_V_1_LIB_TIMEOUT');
        $numberOfRetries = getenv('ONFON_DEVELOPER_V_1_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('ONFON_DEVELOPER_V_1_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('ONFON_DEVELOPER_V_1_LIB_ENVIRONMENT');
        $accessToken = getenv('ONFON_DEVELOPER_V_1_LIB_ACCESS_TOKEN');

        if ($timeout !== false && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if ($environment !== false) {
            $builder->environment($environment);
        }

        if ($accessToken !== false) {
            $builder->accessToken($accessToken);
        }

        return $builder;
    }
}
