<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use OnfonDeveloperV1Lib\Exceptions\ApiException;
use OnfonDeveloperV1Lib\Exceptions\FailedAuthorizationException;
use OnfonDeveloperV1Lib\Exceptions\NotRegisteredSourceException;
use OnfonDeveloperV1Lib\Exceptions\ZeroBalanceException;
use OnfonDeveloperV1Lib\Models\SendSMSRequest;
use OnfonDeveloperV1Lib\Models\SuccessfulResponse;
use OnfonDeveloperV1Lib\Models\SuccessfulResponse1;

class BalanceSendSMSController extends BaseController
{
    /**
     * Send SMS through your application by making a `HTTP POST` request to the following endpoints:
     *
     * > Endpoint: /v2_send
     *
     * ## Request parameters
     *
     * In addition to the [Authorization headers](/docs/request_headers), the body of the request should
     * contain the following fields:
     *
     * | Description
     * |
     * | ---------------------------------------------------------------------------------------------------
     * ---------------------------------- |
     * | **to** `String` `Required` <br>Destination phone number, only one phone is supported at the moment
     * |
     * | **from** `String` `Required` <br>Sender Id or Sender Name sending out the message.
     * |
     * | **content** `String` `Required` <br>The message to be sent.
     * |
     * | **dlr-url** `String` `Optional` <br>URL to receive dlr (delivery receipt).
     * |
     * | **dlr-method** `String` `Optional` <br>The DLR is transmitted through http to a third party
     * application using `GET` or `POST` method. |
     *
     * <!-- | **dlr-level** `Integer` `Optional` <br> Priority of the level. Possible values are `1` to
     * enable and `0` to disable. The default value is `1` | -->
     *
     * ## Api Response
     *
     * `{ "message_id": "61854a56-75be-4342-8831-9a16a4fa06e6" }`
     *
     * @param SendSMSRequest $body
     *
     * @return SuccessfulResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function sendSMS(SendSMSRequest $body): SuccessfulResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v2_send')
            ->auth('global')
            ->parameters(BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(400, ErrorType::init('Bad Request', NotRegisteredSourceException::class))
            ->throwErrorOn(401, ErrorType::init('Unauthorized', FailedAuthorizationException::class))
            ->throwErrorOn(403, ErrorType::init('Forbidden', ZeroBalanceException::class))
            ->type(SuccessfulResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * To check your account balance, send a request to the following endpoint with [Authorization
     * header](/auth) already set.
     *
     * #### With Basic Auth
     *
     * > Authorization: Basic b25mb246IUBwYXMxMjM=
     *
     * #### With Bearer Token
     *
     * > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
     * eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.
     * SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
     *
     * @return SuccessfulResponse1 Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function checkBalance(): SuccessfulResponse1
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/v2_balance')->auth('global');

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(401, ErrorType::init('Unauthorized', FailedAuthorizationException::class))
            ->type(SuccessfulResponse1::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
