<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class SenderId implements \JsonSerializable
{
    /**
     * @var string
     */
    private $senderValue;

    /**
     * @var string
     */
    private $clientId;

    /**
     * @var string
     */
    private $purpose;

    /**
     * @param string $senderValue
     * @param string $clientId
     * @param string $purpose
     */
    public function __construct(string $senderValue, string $clientId, string $purpose)
    {
        $this->senderValue = $senderValue;
        $this->clientId = $clientId;
        $this->purpose = $purpose;
    }

    /**
     * Returns Sender Value.
     */
    public function getSenderValue(): string
    {
        return $this->senderValue;
    }

    /**
     * Sets Sender Value.
     *
     * @required
     * @maps senderValue
     */
    public function setSenderValue(string $senderValue): void
    {
        $this->senderValue = $senderValue;
    }

    /**
     * Returns Client Id.
     */
    public function getClientId(): string
    {
        return $this->clientId;
    }

    /**
     * Sets Client Id.
     *
     * @required
     * @maps clientId
     */
    public function setClientId(string $clientId): void
    {
        $this->clientId = $clientId;
    }

    /**
     * Returns Purpose.
     */
    public function getPurpose(): string
    {
        return $this->purpose;
    }

    /**
     * Sets Purpose.
     *
     * @required
     * @maps purpose
     */
    public function setPurpose(string $purpose): void
    {
        $this->purpose = $purpose;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['senderValue'] = $this->senderValue;
        $json['clientId']    = $this->clientId;
        $json['purpose']     = $this->purpose;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
