<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class SuccessfulResponse1 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $balance;

    /**
     * @var int
     */
    private $smsCount;

    /**
     * @param int $balance
     * @param int $smsCount
     */
    public function __construct(int $balance, int $smsCount)
    {
        $this->balance = $balance;
        $this->smsCount = $smsCount;
    }

    /**
     * Returns Balance.
     */
    public function getBalance(): int
    {
        return $this->balance;
    }

    /**
     * Sets Balance.
     *
     * @required
     * @maps balance
     */
    public function setBalance(int $balance): void
    {
        $this->balance = $balance;
    }

    /**
     * Returns Sms Count.
     */
    public function getSmsCount(): int
    {
        return $this->smsCount;
    }

    /**
     * Sets Sms Count.
     *
     * @required
     * @maps sms_count
     */
    public function setSmsCount(int $smsCount): void
    {
        $this->smsCount = $smsCount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['balance']   = $this->balance;
        $json['sms_count'] = $this->smsCount;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
