<?php

declare(strict_types=1);

/*
 * OnfonDeveloperV1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OnfonDeveloperV1Lib\Models;

use stdClass;

class SuccessfulResponse2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $groupId;

    /**
     * @var string
     */
    private $groupName;

    /**
     * @var string
     */
    private $clientId;

    /**
     * @var string|null
     */
    private $client;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $parentId;

    /**
     * @var int
     */
    private $contacts;

    /**
     * @var string
     */
    private $updateDate;

    /**
     * @var string
     */
    private $createDate;

    /**
     * @param string $groupId
     * @param string $groupName
     * @param string $clientId
     * @param string $description
     * @param string $parentId
     * @param int $contacts
     * @param string $updateDate
     * @param string $createDate
     */
    public function __construct(
        string $groupId,
        string $groupName,
        string $clientId,
        string $description,
        string $parentId,
        int $contacts,
        string $updateDate,
        string $createDate
    ) {
        $this->groupId = $groupId;
        $this->groupName = $groupName;
        $this->clientId = $clientId;
        $this->description = $description;
        $this->parentId = $parentId;
        $this->contacts = $contacts;
        $this->updateDate = $updateDate;
        $this->createDate = $createDate;
    }

    /**
     * Returns Group Id.
     */
    public function getGroupId(): string
    {
        return $this->groupId;
    }

    /**
     * Sets Group Id.
     *
     * @required
     * @maps groupId
     */
    public function setGroupId(string $groupId): void
    {
        $this->groupId = $groupId;
    }

    /**
     * Returns Group Name.
     */
    public function getGroupName(): string
    {
        return $this->groupName;
    }

    /**
     * Sets Group Name.
     *
     * @required
     * @maps groupName
     */
    public function setGroupName(string $groupName): void
    {
        $this->groupName = $groupName;
    }

    /**
     * Returns Client Id.
     */
    public function getClientId(): string
    {
        return $this->clientId;
    }

    /**
     * Sets Client Id.
     *
     * @required
     * @maps clientId
     */
    public function setClientId(string $clientId): void
    {
        $this->clientId = $clientId;
    }

    /**
     * Returns Client.
     */
    public function getClient(): ?string
    {
        return $this->client;
    }

    /**
     * Sets Client.
     *
     * @maps client
     */
    public function setClient(?string $client): void
    {
        $this->client = $client;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Parent Id.
     */
    public function getParentId(): string
    {
        return $this->parentId;
    }

    /**
     * Sets Parent Id.
     *
     * @required
     * @maps parentId
     */
    public function setParentId(string $parentId): void
    {
        $this->parentId = $parentId;
    }

    /**
     * Returns Contacts.
     */
    public function getContacts(): int
    {
        return $this->contacts;
    }

    /**
     * Sets Contacts.
     *
     * @required
     * @maps contacts
     */
    public function setContacts(int $contacts): void
    {
        $this->contacts = $contacts;
    }

    /**
     * Returns Update Date.
     */
    public function getUpdateDate(): string
    {
        return $this->updateDate;
    }

    /**
     * Sets Update Date.
     *
     * @required
     * @maps updateDate
     */
    public function setUpdateDate(string $updateDate): void
    {
        $this->updateDate = $updateDate;
    }

    /**
     * Returns Create Date.
     */
    public function getCreateDate(): string
    {
        return $this->createDate;
    }

    /**
     * Sets Create Date.
     *
     * @required
     * @maps createDate
     */
    public function setCreateDate(string $createDate): void
    {
        $this->createDate = $createDate;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['groupId']     = $this->groupId;
        $json['groupName']   = $this->groupName;
        $json['clientId']    = $this->clientId;
        $json['client']      = $this->client;
        $json['description'] = $this->description;
        $json['parentId']    = $this->parentId;
        $json['contacts']    = $this->contacts;
        $json['updateDate']  = $this->updateDate;
        $json['createDate']  = $this->createDate;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
